const replaceChatItemAction = (value: any, emitter: NodeJS.EventEmitter, channel: string) => {
  emitter.emit("replaceChatItemAction", { channel, ...value });
}

export default replaceChatItemAction


// replaceChatItemAction {"targetItemId":"ChwKGkNPRFRsSW1ILW9BREZTckR3Z1Fkc3JFQmlB","replacementItem":{"liveChatTextMessageRenderer":{"message":{"runs":[{"text":"ja testou fazer cardio com um dildo no acento?, um amigo disse que da certo"}]},"authorName":{"simpleText":"davi almeida"},"authorPhoto":{"thumbnails":[{"url":"https://yt4.ggpht.com/ytc/AOPolaTXI_9Xh259qkNhH8UMLvyb8nKQaztHGZCyTQzhqA=s32-c-k-c0x00ffffff-no-rj","width":32,"height":32},{"url":"https://yt4.ggpht.com/ytc/AOPolaTXI_9Xh259qkNhH8UMLvyb8nKQaztHGZCyTQzhqA=s64-c-k-c0x00ffffff-no-rj","width":64,"height":64}]},"contextMenuEndpoint":{"clickTrackingParams":"CAEQl98BIhMI8PCSuYj6gAMVGpyVAh0jcgck","commandMetadata":{"webCommandMetadata":{"ignoreNavigation":true}},"liveChatItemContextMenuEndpoint":{"params":"Q2g0S0hBb2FRMDlFVkd4SmJVZ3RiMEZFUmxOeVJIZG5VV1J6Y2tWQ2FVRWFLU29uQ2hoVlExQXRTRXBKVWxoT0xXRndWVkJUUTA5bGFFVkVXbmNTQzBob01XOXpjV2xKVVRaRklBSW9BVElhQ2hoVlExQjZkM1JpZFRORFJXRjVaazFFTmtWSVNHNU9ja0U0QWtnQVVBRSUzRA=="}},"id":"ChwKGkNPRFRsSW1ILW9BREZTckR3Z1Fkc3JFQmlB","timestampUsec":"1693043646630293","authorExternalChannelId":"UCPzwtbu3CEayfMD6EHHnNrA","contextMenuAccessibility":{"accessibilityData":{"label":"Chat actions"}},"trackingParams":"CAEQl98BIhMI8PCSuYj6gAMVGpyVAh0jcgck"}}}


// {"targetItemId":"ChwKGkNKanQwYjJVLW9BREZjckN3Z1FkcWdFRHBn","replacementItem":{"liveChatTextMessageRenderer":{"message":{"runs":[{"text":"mano... nunca conheci um Aidético, mas deve ser
// foda essa merda"}]},"authorName":{"simpleText":"Evolution Games"},"authorPhoto":{"thumbnails":[{"url":"https://yt4.ggpht.com/ytc/AOPolaSMcMz9z_dY78G8PQQ5iKmuqeZtdyJjF5DWZJLgXw=s32-c-k-c0x00ffffff-no-rj","width":32,"height":32},{"url":"https://yt4.ggpht.com/ytc/AOPolaSMcMz9z_dY78G8PQQ5iKmuqeZtdyJjF5DWZJLgXw=s64-c-k-c0x00ffffff-no-rj","width":64,"height":64}]},"contextMenuEndpoint":{"clickTrackingParams":"CAEQl98BIhMIo464ppX6gAMValtIAB0h6wwL","commandMetadata":{"webCommandMetadata":{"ignoreNavigation":true}},"liveChatItemContextMenuEndpoint":{"params":"Q2g0S0hBb2FRMHBxZERCaU1sVXRiMEZFUm1OeVEzZG5VV1J4WjBWRWNHY2FLU29uQ2hoVlExQXRTRXBKVWxoT0xXRndWVkJUUTA5bGFFVkVXbmNTQzBob01XOXpjV2xKVVRaRklBSW9BVElhQ2hoVlEwWkxVa2MzWWtWaVFVTnZYMGxZWWpVeU0wcFJTbWM0QWtnQVVBRSUzRA=="}},"id":"ChwKGkNKanQwYjJVLW9BREZjckN3Z1FkcWdFRHBn","timestampUsec":"1693047246344278","authorExternalChannelId":"UCFKRG7bEbACo_IXb523JQJg","contextMenuAccessibility":{"accessibilityData":{"label":"Chat actions"}},"trackingParams":"CAEQl98BIhMIo464ppX6gAMValtIAB0h6wwL"}}}